# Generated by Django 4.2.2 on 2023-07-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
