# Generated by Django 4.2.2 on 2023-07-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelcon',
        ),
    ]
