# Generated by Django 4.2.2 on 2023-07-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_pelcon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['user']},
        ),
    ]
