# Generated by Django 4.2.2 on 2023-07-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_jobapplication_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
