# Generated by Django 4.2.2 on 2023-07-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
