# Generated by Django 4.2.2 on 2023-07-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
