# Generated by Django 4.2.2 on 2023-08-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_jobapplication_application_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRecruiter',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
