# Generated by Django 4.2.2 on 2023-08-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_jobseeker_jobrecruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
